// Generated by Haxe 3.4.7
(function () { "use strict";
function $extend(from, fields) {
	function Inherit() {} Inherit.prototype = from; var proto = new Inherit();
	for (var name in fields) proto[name] = fields[name];
	if( fields.toString !== Object.prototype.toString ) proto.toString = fields.toString;
	return proto;
}
var App = function() { };
App.main = function() {
	var wrapper = window.document.createElement("div");
	window.document.body.appendChild(wrapper);
	var theme = mui_core_styles_MuiTheme.createMuiTheme({ palette : { primary : { main : "#a53fa1"}, secondary : { main : "#84BD55"}, error : { main : "#FF0000"}}, typography : { fontFamily : ["Cabin","\"Helvetica Neue\"","Arial","sans-serif"], fontSize : 16}});
	var app = react__$ReactType_ReactType_$Impl_$.fromComp(mui_core_styles_MuiThemeProvider);
	var app1 = react__$ReactType_ReactType_$Impl_$.fromComp(React.Fragment);
	var app2 = React.createElement(react__$ReactType_ReactType_$Impl_$.fromComp(mui_core_CssBaseline),{ });
	var app3 = react__$ReactType_ReactType_$Impl_$.fromString("div");
	var app4 = react__$ReactType_ReactType_$Impl_$.fromComp(mui_core_Grid);
	var app5 = React.createElement(react__$ReactType_ReactType_$Impl_$.fromComp(mui_core_Grid),{ item : true},React.createElement(react__$ReactType_ReactType_$Impl_$.fromComp(mui_core_Button),{ color : "primary", variant : "outlined", fullWidth : true},"Test"));
	var app6 = react__$ReactType_ReactType_$Impl_$.fromComp(mui_core_Grid);
	var app7 = React.createElement(app3,{ style : { maxWidth : 1240, margin : "auto", padding : "0 10px"}},React.createElement(app4,{ container : true},app5,React.createElement(app6,{ item : true},React.createElement(react__$ReactType_ReactType_$Impl_$.fromFunctionWithProps(MyComponent._renderWrapper),{ },"Test 2"))));
	var app8 = react__$ReactType_ReactType_$Impl_$.fromString("div");
	var app9 = react__$ReactType_ReactType_$Impl_$.fromComp(mui_core_Grid);
	var app10 = React.createElement(react__$ReactType_ReactType_$Impl_$.fromComp(mui_core_Grid),{ item : true, xs : 12, sm : 4, md : 3},React.createElement(react__$ReactType_ReactType_$Impl_$.fromFunctionWithProps(Product._renderWrapper),{ }));
	var app11 = React.createElement(react__$ReactType_ReactType_$Impl_$.fromComp(mui_core_Grid),{ item : true, xs : 12, sm : 4, md : 3},React.createElement(react__$ReactType_ReactType_$Impl_$.fromFunctionWithProps(Product._renderWrapper),{ }));
	var app12 = React.createElement(react__$ReactType_ReactType_$Impl_$.fromComp(mui_core_Grid),{ item : true, xs : 12, sm : 4, md : 3},React.createElement(react__$ReactType_ReactType_$Impl_$.fromFunctionWithProps(Product._renderWrapper),{ }));
	var app13 = react__$ReactType_ReactType_$Impl_$.fromComp(mui_core_Grid);
	var app14 = React.createElement(app1,{ },app2,app7,React.createElement(app8,{ style : { maxWidth : 1240, margin : "auto", padding : "0 10px"}},React.createElement(app9,{ container : true, style : { marginBottom : 20}, spacing : 24},app10,app11,app12,React.createElement(app13,{ item : true, xs : 12, sm : 4, md : 3},React.createElement(react__$ReactType_ReactType_$Impl_$.fromFunctionWithProps(Product._renderWrapper),{ })))));
	var app15 = ReactDOM.render(React.createElement(app,{ theme : theme},app14),wrapper);
};
var HxOverrides = function() { };
HxOverrides.iter = function(a) {
	return { cur : 0, arr : a, hasNext : function() {
		return this.cur < this.arr.length;
	}, next : function() {
		return this.arr[this.cur++];
	}};
};
var JsxStaticInit_$_$ = function() { };
var React_Component = require("react").Component;
var mui_core_styles_Styles = require("@material-ui/core/styles");
var react__$ReactType_ReactType_$Impl_$ = {};
react__$ReactType_ReactType_$Impl_$.fromString = function(s) {
	if(s == null) {
		return react__$ReactType_ReactType_$Impl_$.isNull();
	}
	return s;
};
react__$ReactType_ReactType_$Impl_$.fromFunction = function(f) {
	if(f == null) {
		return react__$ReactType_ReactType_$Impl_$.isNull();
	}
	return f;
};
react__$ReactType_ReactType_$Impl_$.fromFunctionWithProps = function(f) {
	if(f == null) {
		return react__$ReactType_ReactType_$Impl_$.isNull();
	}
	return f;
};
react__$ReactType_ReactType_$Impl_$.fromComp = function(cls) {
	if(cls == null) {
		return react__$ReactType_ReactType_$Impl_$.isNull();
	}
	if(cls.__jsxStatic != null) {
		return cls.__jsxStatic;
	}
	return cls;
};
react__$ReactType_ReactType_$Impl_$.isNull = function() {
	window.console.error("Runtime value for ReactType is null." + " Something may be wrong with your externs.");
	return "div";
};
var MyComponent = function(props,context) {
	React_Component.call(this,props,context);
};
MyComponent.styles = function(theme) {
	return { root : { padding : 4 * theme.spacing.unit, background : theme.palette.background.dark, color : "#84BD55", "&::before" : { content : "\"pseudo-element\"", display : "block", position : "relative"}}, selected : { fontSize : "300%"}};
};
MyComponent.__super__ = React_Component;
MyComponent.prototype = $extend(React_Component.prototype,{
	render: function() {
		var classes = " " + this.props.classes.root + (this.props.selected ? " " + this.props.classes.selected : "");
		return React.createElement(react__$ReactType_ReactType_$Impl_$.fromComp(mui_core_Button),{ variant : "outlined", className : classes, fullWidth : true},this.props.children);
	}
});
var Product = function(props,context) {
	React_Component.call(this,props,context);
};
Product.styles = function(theme) {
	return { button : { size : "small", textTransform : "none", color : "#84BD55"}, card : { backgroundColor : "#F8F4E5"}, media : { height : 170, padding : 1}, cardContent : { padding : 10, paddingBottom : 5}, productBuy : { boxShadow : "none"}, starProduct : { width : 30, height : 30, color : "#F9D800", backgroundColor : "#ffffff", marginLeft : "auto", fontSize : 16}, farmerAvatar : { color : "#404040", backgroundColor : "#ededed", border : "3 solid #ffffff", width : 70, height : 70, marginLeft : "auto", fontSize : 10}, cagAvatarContainer : { margin : "3%", height : "43%", display : "flex"}, cagProductTitle : { lineHeight : "normal", fontSize : "1.08rem", fontStyle : "normal", fontWeight : 400, textTransform : "uppercase", marginBottom : 3, maxHeight : 40, overflow : "hidden"}, cagProductLabel : { marginLeft : -3, "& .labelChip:hover" : { backgroundColor : "#FFFFFF"}, "& .labelChip" : { fontSize : "0.7rem", margin : "5px 2px", padding : "0 5px"}}, cagProductDesc : { fontSize : "0.9rem", color : "#7F7F7F", marginBottom : 0, maxHeight : 65, overflow : "hidden"}, cagProductInfoWrap : { justifyContent : "space-between", padding : "0 10px"}, cagProductInfo : { fontSize : "1.3rem", "& .cagProductUnit" : { marginRight : "2rem"}, "& .cagProductPrice" : { color : "#E95219"}}, cagProductPriceRate : { fontSize : "0.75rem", color : "#7F7F7F", marginTop : -5, marginLeft : 5}};
};
Product.__super__ = React_Component;
Product.prototype = $extend(React_Component.prototype,{
	render: function() {
		var classes = this.props.classes;
		var CardMediaClasses = " " + classes.media;
		var tmp = react__$ReactType_ReactType_$Impl_$.fromComp(mui_core_Card);
		var tmp1 = { elevation : 0, className : classes.card};
		var tmp2 = react__$ReactType_ReactType_$Impl_$.fromComp(mui_core_CardActionArea);
		var tmp3 = react__$ReactType_ReactType_$Impl_$.fromComp(mui_core_CardMedia);
		var tmp4 = React.createElement(react__$ReactType_ReactType_$Impl_$.fromString("div"),{ className : classes.cagAvatarContainer},React.createElement(react__$ReactType_ReactType_$Impl_$.fromComp(mui_core_Avatar),{ className : classes.starProduct},React.createElement(react__$ReactType_ReactType_$Impl_$.fromString("i"),{ className : "icon icon-truck-solid"})));
		var tmp5 = react__$ReactType_ReactType_$Impl_$.fromString("div");
		var tmp6 = React.createElement(tmp3,{ className : CardMediaClasses, image : "/img/produit-oranges2.jpg", title : "Orange Naveline de Catania"},tmp4,React.createElement(tmp5,{ className : classes.cagAvatarContainer},React.createElement(react__$ReactType_ReactType_$Impl_$.fromComp(mui_core_Avatar),{ src : "/img/la-ferme-des-2-rivieres.jpg", className : classes.farmerAvatar})));
		var tmp7 = react__$ReactType_ReactType_$Impl_$.fromComp(mui_core_CardContent);
		var tmp8 = { className : classes.cardContent};
		var tmp9 = React.createElement(react__$ReactType_ReactType_$Impl_$.fromComp(mui_core_Typography),{ component : react__$ReactType_ReactType_$Impl_$.fromString("h3"), className : classes.cagProductTitle},"Orange  Naveline de Catatania");
		var tmp10 = React.createElement(react__$ReactType_ReactType_$Impl_$.fromComp(mui_core_Typography),{ component : react__$ReactType_ReactType_$Impl_$.fromString("p"), className : classes.cagProductDesc},"La Ferme");
		var tmp11 = react__$ReactType_ReactType_$Impl_$.fromComp(mui_core_Typography);
		var tmp12 = { component : react__$ReactType_ReactType_$Impl_$.fromString("p"), className : classes.cagProductLabel};
		var tmp13 = React.createElement(react__$ReactType_ReactType_$Impl_$.fromFunctionWithProps(SubCateg._renderWrapper),{ label : "Label rouge", icon : "icon icon-truck-solid", colorClass : "cagLabelRouge"});
		return React.createElement(tmp,tmp1,React.createElement(tmp2,{ },tmp6,React.createElement(tmp7,tmp8,tmp9,tmp10,React.createElement(tmp11,tmp12,tmp13,React.createElement(react__$ReactType_ReactType_$Impl_$.fromFunctionWithProps(SubCateg._renderWrapper),{ label : "Bio", icon : "icon icon-truck-solid", colorClass : "cagBio"})))),React.createElement(react__$ReactType_ReactType_$Impl_$.fromComp(mui_core_CardActions),{ className : classes.cagProductInfoWrap},React.createElement(react__$ReactType_ReactType_$Impl_$.fromComp(mui_core_Typography),{ component : react__$ReactType_ReactType_$Impl_$.fromString("p"), className : classes.cagProductInfo},React.createElement(react__$ReactType_ReactType_$Impl_$.fromString("span"),{ className : "cagProductUnit"},"1 kg "),React.createElement(react__$ReactType_ReactType_$Impl_$.fromString("span"),{ className : "cagProductPrice"},"2,50 €")),React.createElement(react__$ReactType_ReactType_$Impl_$.fromFunctionWithProps(QuantityInput._renderWrapper),{ }),React.createElement(react__$ReactType_ReactType_$Impl_$.fromComp(mui_core_Button),{ variant : "contained", color : "primary", className : classes.productBuy, disableRipple : true},React.createElement(react__$ReactType_ReactType_$Impl_$.fromString("i"),{ className : "icon icon-truck-solid"}))),React.createElement(react__$ReactType_ReactType_$Impl_$.fromComp(mui_core_CardActions),{ className : classes.cagProductInfoWrap, style : { marginBottom : 10}},React.createElement(react__$ReactType_ReactType_$Impl_$.fromComp(mui_core_Typography),{ component : react__$ReactType_ReactType_$Impl_$.fromString("p"), className : classes.cagProductPriceRate},"2,50 €/kg")));
	}
});
var QuantityInput = function(props,context) {
	React_Component.call(this,props,context);
};
QuantityInput.styles = function(theme) {
	return { quantityInput : { border : "1px solid " + "#a53fa1", borderRadius : 3, display : "flex", maxWidth : 104, "& div" : { flexGrow : 1}, "& .quantityMoreLess" : { backgroundColor : "#a53fa1", padding : 8, color : "#ffffff", fontSize : "2rem", lineHeight : "1rem", cursor : "pointer", textAlign : "center", transition : "all 0.5s ease", "&::hover" : { backgroundColor : "#a53fa1"}}, "& .quantity" : { fontSize : "1.2rem", lineHeight : "2rem", minWidth : 35, textAlign : "center", verticalAlign : "middle", color : "#a53fa1", backgroundColor : "#fff"}}};
};
QuantityInput.__super__ = React_Component;
QuantityInput.prototype = $extend(React_Component.prototype,{
	render: function() {
		var classes = this.props.classes;
		return React.createElement(react__$ReactType_ReactType_$Impl_$.fromString("div"),{ className : classes.quantityInput},React.createElement(react__$ReactType_ReactType_$Impl_$.fromString("div"),{ className : "quantityMoreLess"}," - "),React.createElement(react__$ReactType_ReactType_$Impl_$.fromString("div"),{ className : "quantity"}," 1 "),React.createElement(react__$ReactType_ReactType_$Impl_$.fromString("div"),{ className : "quantityMoreLess"}," + "));
	}
});
var SubCateg = function(props,context) {
	React_Component.call(this,props,context);
};
SubCateg.styles = function(theme) {
	return { labelShip : { backgroundColor : "#FFFFFF", fontSize : "0.95rem", margin : "10 8", padding : "5 10", borderRadius : 16, textDecoration : "none", display : "inline-block", transition : "all 0.5s ease", "&::hover" : { backgroundColor : "#FFFFFF"}, "&.cagSelect" : { color : "#E56403"}, "&.cagLabelRouge" : { color : "#E53909"}, "&.cagBio" : { color : "#16993B"}}};
};
SubCateg.__super__ = React_Component;
SubCateg.prototype = $extend(React_Component.prototype,{
	render: function() {
		var linkClasses = " " + this.props.classes.labelShip + (" " + this.props.colorClass);
		var iconClasses = " " + this.props.icon;
		var _tmp = Object.assign({ },this.props);
		delete _tmp["onclick"];
		delete _tmp["label"];
		delete _tmp["icon"];
		delete _tmp["colorClass"];
		delete _tmp["classes"];
		var others = _tmp;
		return React.createElement(react__$ReactType_ReactType_$Impl_$.fromString("a"),Object.assign({ },others,{ onClick : this.props.onclick, className : linkClasses}),React.createElement(react__$ReactType_ReactType_$Impl_$.fromString("i"),{ className : iconClasses})," ",this.props.label);
	}
});
var classnames_ClassNames = function() { };
classnames_ClassNames.arrayToMap = function(arr) {
	var map = { };
	var _g = 0;
	while(_g < arr.length) {
		var a = arr[_g];
		++_g;
		map[a] = true;
	}
	return map;
};
classnames_ClassNames.fromMaps = function(classMaps,nullIfEmpty) {
	if(nullIfEmpty == null) {
		nullIfEmpty = false;
	}
	var o = { };
	if(classnames_ClassNames.hasOwnProperty == null) {
		classnames_ClassNames.hasOwnProperty = Object.prototype.hasOwnProperty;
	}
	var _g = 0;
	while(_g < classMaps.length) {
		var classMap = classMaps[_g];
		++_g;
		for (var k in classMap) {
		if(classnames_ClassNames.hasOwnProperty.call(classMap,k)) {
			var val = classMap[k];
			o[k] = val;
		}
		}
	}
	return classnames_ClassNames.fromMap(o,nullIfEmpty);
};
classnames_ClassNames.fromMap = function(classMap,nullIfEmpty) {
	if(nullIfEmpty == null) {
		nullIfEmpty = false;
	}
	var classNames = [];
	var hasClassNames = false;
	if(classnames_ClassNames.hasOwnProperty == null) {
		classnames_ClassNames.hasOwnProperty = Object.prototype.hasOwnProperty;
	}
	for (var k in classMap) {
	if(classnames_ClassNames.hasOwnProperty.call(classMap,k)) {
		if(classMap[k]) {
			classNames.push(k);
			hasClassNames = true;
		}
	}
	}
	if(hasClassNames) {
		return classNames.join(" ");
	}
	if(nullIfEmpty) {
		return null;
	} else {
		return "";
	}
};
var mui_core_Avatar = require("@material-ui/core").Avatar;
var mui_core_Button = require("@material-ui/core").Button;
var mui_core_Card = require("@material-ui/core").Card;
var mui_core_CardActionArea = require("@material-ui/core").CardActionArea;
var mui_core_CardActions = require("@material-ui/core").CardActions;
var mui_core_CardContent = require("@material-ui/core").CardContent;
var mui_core_CardMedia = require("@material-ui/core").CardMedia;
var mui_core_CssBaseline = require("@material-ui/core").CssBaseline;
var mui_core_Grid = require("@material-ui/core").Grid;
var mui_core_Typography = require("@material-ui/core").Typography;
var mui_core_styles_Classes = function() { };
var mui_core_styles_ClassesDef = function() { };
var mui_core_styles_MuiTheme = require("@material-ui/core/styles");
var mui_core_styles_MuiThemeProvider = require("@material-ui/core/styles").MuiThemeProvider;
var react_Partial = function() { };
var react_PartialMacro = function() { };
var React = require("react");
var ReactDOM = require("react-dom");
var react_ReactMacro = function() { };
var react__$ReactRef_ReactRef_$Impl_$ = {};
react__$ReactRef_ReactRef_$Impl_$.get_current = function(this1) {
	return this1.current;
};
var react__$ReactType_ReactTypeOf_$Impl_$ = {};
react__$ReactType_ReactTypeOf_$Impl_$._new = function(node) {
	var this1 = node;
	return this1;
};
react__$ReactType_ReactTypeOf_$Impl_$.fromFunctionWithProps = function(f) {
	var this1 = react__$ReactType_ReactType_$Impl_$.fromFunctionWithProps(f);
	return this1;
};
react__$ReactType_ReactTypeOf_$Impl_$.fromComp = function(cls) {
	var this1 = react__$ReactType_ReactType_$Impl_$.fromComp(cls);
	return this1;
};
react__$ReactType_ReactTypeOf_$Impl_$.fromFunctionWithoutProps = function(f) {
	var this1 = react__$ReactType_ReactType_$Impl_$.fromFunction(f);
	return this1;
};
react__$ReactType_ReactTypeOf_$Impl_$.fromCompWithoutProps = function(cls) {
	var this1 = react__$ReactType_ReactType_$Impl_$.fromComp(cls);
	return this1;
};
var react_types_css__$Overflow_Overflow_$Impl_$ = {};
react_types_css__$Overflow_Overflow_$Impl_$.fromArray = function(arr) {
	return arr.join(" ");
};
var react_types_css__$TextOverflow_TextOverflow_$Impl_$ = {};
react_types_css__$TextOverflow_TextOverflow_$Impl_$.fromArray = function(arr) {
	return arr.join(" ");
};
MyComponent.displayName = "MyComponent";
MyComponent._renderWrapper = (mui_core_styles_Styles.withStyles(MyComponent.styles))(react__$ReactType_ReactType_$Impl_$.fromComp(MyComponent));
MyComponent.__jsxStatic = MyComponent._renderWrapper;
Product.displayName = "Product";
Product._renderWrapper = (mui_core_styles_Styles.withStyles(Product.styles))(react__$ReactType_ReactType_$Impl_$.fromComp(Product));
Product.__jsxStatic = Product._renderWrapper;
QuantityInput.displayName = "QuantityInput";
QuantityInput._renderWrapper = (mui_core_styles_Styles.withStyles(QuantityInput.styles))(react__$ReactType_ReactType_$Impl_$.fromComp(QuantityInput));
QuantityInput.__jsxStatic = QuantityInput._renderWrapper;
SubCateg.displayName = "SubCateg";
SubCateg._renderWrapper = (mui_core_styles_Styles.withStyles(SubCateg.styles))(react__$ReactType_ReactType_$Impl_$.fromComp(SubCateg));
SubCateg.__jsxStatic = SubCateg._renderWrapper;
react_types_css__$Overflow_Overflow_$Impl_$.Visible = "visible";
react_types_css__$Overflow_Overflow_$Impl_$.Hidden = "hidden";
react_types_css__$Overflow_Overflow_$Impl_$.Scroll = "scroll";
react_types_css__$Overflow_Overflow_$Impl_$.Auto = "auto";
react_types_css__$TextOverflow_TextOverflow_$Impl_$.Clip = "clip";
react_types_css__$TextOverflow_TextOverflow_$Impl_$.Ellipsis = "ellipsis";
App.main();
})();

//# sourceMappingURL=index.js.map